modLoader = "javafml"
loaderVersion = "[33,)"
license = "MIT License"
issueTrackerURL = "https://github.com/nik7007/upgrade_craft/issues"

[[mods]]
modId = "upgradecraft"
version = "${file.jarVersion}"
displayName = "UpgradeCraft"
# updateJSONURL="http://myurl.me/"
displayURL = "https://github.com/nik7007/upgrade_craft/"
logoFile = "upgradecraft_logo.png"
credits = "Thanks to the amazing Forge community"
authors = "Nik7"
description = '''It's time to upgrade minecrat!'''

[[dependencies.upgradecraft]]
modId = "forge"
mandatory = true
versionRange = "[33,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.upgradecraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2]"
ordering = "NONE"
side = "BOTH"
